# version: 0.2

# phases:
#   install:
#     runtime-versions:
#       nodejs: 18
#     commands:
#       - npm install

#   build:
#     commands:
#       - npm run build

# artifacts:
#   files:
#     - '**/*'
#   base-directory: 'build'


version: 0.2
phases:
  install:
    #If you use the Ubuntu standard image 2.0 or later, you must specify runtime-versions.
    #If you specify runtime-versions and use an image other than Ubuntu standard image 2.0, the build fails.
    runtime-versions:
      nodejs: 18
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install @material-ui/core --force
  build:
    commands:
      - echo Build started on 'date'
      
      - npm prune --production

    artifacts:
      files:
         - "build/*"
         - "build/**/*"

    cache:
      paths:
        - node_modules

         
